# Generated by Django 5.1.15 on 2026-08-24 19:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
        ('tourists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('current_city', models.CharField(default='Agra', max_length=100)),
                ('state', models.CharField(default='Uttar Pradesh', max_length=100)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('ACTIVE', 'Active / In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='ACTIVE', max_length=20)),
                ('visited_count', models.IntegerField(default=0)),
                ('total_count', models.IntegerField(default=1)),
                ('expected_check_in_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_journeys', to='destinations.destination')),
                ('tourist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journeys', to='tourists.touristprofile')),
            ],
            options={
                'verbose_name': 'Journey',
                'verbose_name_plural': 'Journeys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CheckInSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_check_in_time', models.DateTimeField(db_index=True)),
                ('actual_check_in_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Check-in'), ('COMPLETED', 'Completed On Time'), ('MISSED', 'Missed Check-in'), ('ESCALATED', 'Escalated to Emergency Contacts')], db_index=True, default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tourist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_in_schedules', to='tourists.touristprofile')),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_in_schedules', to='journeys.journey')),
            ],
            options={
                'verbose_name': 'Check-in Schedule',
                'verbose_name_plural': 'Check-in Schedules',
                'ordering': ['expected_check_in_time'],
            },
        ),
        migrations.CreateModel(
            name='JourneyLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('event_type', models.CharField(choices=[('CHECK_IN', 'Tourist Safety Check-in'), ('DESTINATION_VISIT', 'Destination QR Visit'), ('LOCATION_UPDATE', 'GPS Location Update'), ('JOURNEY_START', 'Journey Started'), ('JOURNEY_END', 'Journey Completed')], default='CHECK_IN', max_length=30)),
                ('status', models.CharField(default='ongoing', max_length=20)),
                ('safety_check', models.CharField(choices=[('safe', 'Safe'), ('caution', 'Caution Area'), ('danger', 'Hazard / Danger Warning')], default='safe', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journey_events', to='destinations.destination')),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='journeys.journey')),
                ('tourist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journey_locations', to='tourists.touristprofile')),
            ],
            options={
                'verbose_name': 'Journey Location Log',
                'verbose_name_plural': 'Journey Location Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
