# Generated by Django 5.1.15 on 2026-08-24 19:24

import django.db.models.deletion
import tourists.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TouristProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digital_id', models.CharField(db_index=True, default=tourists.utils.generate_digital_tourist_id, editable=False, max_length=32, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=25)),
                ('nationality', models.CharField(default='Indian', max_length=100)),
                ('passport_hash', models.CharField(blank=True, default='P••••••••3291', max_length=64)),
                ('aadhaar_hash', models.CharField(blank=True, default='XXXX-XXXX-4819', max_length=64)),
                ('gender', models.CharField(default='Male', max_length=20)),
                ('dob', models.DateField(blank=True, null=True)),
                ('blood_group', models.CharField(default='O+ Positive', max_length=20)),
                ('medical_notes', models.TextField(blank=True, default='No known allergies.')),
                ('avatar_url', models.CharField(default='https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80', max_length=500)),
                ('verification_status', models.CharField(choices=[('verified', 'Verified'), ('pending', 'Pending Verification'), ('unverified', 'Unverified')], default='verified', max_length=20)),
                ('verified_by', models.CharField(default='Ministry of Tourism, Govt of India & UP Tourist Police', max_length=255)),
                ('safety_status', models.CharField(choices=[('safe', 'Safe'), ('caution', 'Caution'), ('danger', 'Danger / SOS Active')], default='safe', max_length=20)),
                ('check_in_due_minutes', models.IntegerField(default=60)),
                ('last_check_in_time', models.DateTimeField(blank=True, null=True)),
                ('last_check_in_location', models.CharField(blank=True, default='Taj East Gate Geofence', max_length=255)),
                ('last_latitude', models.FloatField(blank=True, default=27.1751, null=True)),
                ('last_longitude', models.FloatField(blank=True, default=78.0421, null=True)),
                ('share_live_location', models.BooleanField(default=True)),
                ('auto_alert_on_missed_check_in', models.BooleanField(default=True)),
                ('allow_emergency_service_beacon', models.BooleanField(default=True)),
                ('anonymous_safety_metrics', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tourist_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tourist Profile',
                'verbose_name_plural': 'Tourist Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('relationship', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=25)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_primary', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tourist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='tourists.touristprofile')),
            ],
            options={
                'verbose_name': 'Emergency Contact',
                'verbose_name_plural': 'Emergency Contacts',
                'ordering': ['-is_primary', 'name'],
            },
        ),
    ]
