# Generated by Django 5.1.6 on 2026-08-17 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guide", "0001_initial"),
        ("identity", "0002_tourist_emergencycontact_digitalid"),
        ("listings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="guideprofile",
            options={"ordering": ["-rating_avg", "-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="tourpackage",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RenameField(
            model_name="guideprofile",
            old_name="rating",
            new_name="rating_avg",
        ),
        migrations.RenameField(
            model_name="tourpackage",
            old_name="max_people",
            new_name="max_group_size",
        ),
        migrations.RemoveField(
            model_name="guideprofile",
            name="is_available",
        ),
        migrations.RemoveField(
            model_name="guideprofile",
            name="languages",
        ),
        migrations.RemoveField(
            model_name="guideprofile",
            name="license_number",
        ),
        migrations.RemoveField(
            model_name="tourpackage",
            name="destination",
        ),
        migrations.RemoveField(
            model_name="tourpackage",
            name="duration_days",
        ),
        migrations.AddField(
            model_name="guideprofile",
            name="languages_spoken",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Comma-separated languages spoken, e.g. English, Hindi, French",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="guideprofile",
            name="regions_served",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Comma-separated regions or operational zones, e.g. Jaipur, Rajasthan, Delhi",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="guideprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="guideprofile",
            name="verified",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Designates whether this guide has been officially verified by an admin",
            ),
        ),
        migrations.AddField(
            model_name="guideprofile",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_guides",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tourpackage",
            name="duration",
            field=models.CharField(
                default="Half Day",
                help_text="Duration description, e.g. '4 hours', '1 day', '3 days'",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="tourpackage",
            name="poi_refs",
            field=models.ManyToManyField(
                blank=True,
                help_text="Points of interest / destination listings included in this tour",
                related_name="tour_packages",
                to="listings.listing",
            ),
        ),
        migrations.AddField(
            model_name="tourpackage",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="tourpackage",
            name="guide",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tour_packages",
                to="guide.guideprofile",
            ),
        ),
        migrations.CreateModel(
            name="GuideBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("confirmed", "Confirmed"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="requested",
                        max_length=20,
                    ),
                ),
                ("scheduled_date", models.DateField()),
                ("number_of_people", models.PositiveIntegerField(default=1)),
                ("special_requests", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tour_package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="guide.tourpackage",
                    ),
                ),
                (
                    "tourist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guide_bookings",
                        to="identity.tourist",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
