# Generated by Django 5.1.6 on 2026-08-17 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("TOURIST", "Tourist"),
                            ("GUIDE", "Local Guide"),
                            ("ADMIN", "Administrator"),
                            ("RESPONDER", "Emergency Responder"),
                        ],
                        default="TOURIST",
                        max_length=20,
                    ),
                ),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                (
                    "region_scope",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Jurisdiction region for RESPONDER/ADMIN (e.g., 'Jaipur', 'Amer', or blank for all regions)",
                        max_length=100,
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "emergency_contact_name",
                    models.CharField(blank=True, max_length=120),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(blank=True, max_length=20),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
