# Generated by Django 5.1.6 on 2026-08-17 10:10

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tourist",
            fields=[
                (
                    "tourist_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("nationality", models.CharField(max_length=100)),
                (
                    "id_proof_type",
                    models.CharField(
                        choices=[
                            ("PASSPORT", "Passport"),
                            ("NATIONAL_ID", "National Identity Card"),
                            ("DRIVING_LICENSE", "Driving License"),
                            ("AADHAAR", "Aadhaar Card"),
                            ("OTHER", "Other Official ID"),
                        ],
                        default="PASSPORT",
                        max_length=50,
                    ),
                ),
                ("id_proof_number", models.CharField(blank=True, max_length=100)),
                ("phone", models.CharField(max_length=25)),
                (
                    "current_region",
                    models.CharField(
                        db_index=True,
                        default="Jaipur",
                        help_text="Current destination region for this tourist",
                        max_length=100,
                    ),
                ),
                ("preferred_language", models.CharField(default="en", max_length=50)),
                ("trip_start", models.DateField()),
                ("trip_end", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tourist_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmergencyContact",
            fields=[
                (
                    "contact_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("phone", models.CharField(max_length=25)),
                ("relation", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tourist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emergency_contacts",
                        to="identity.tourist",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DigitalID",
            fields=[
                (
                    "id_token",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "qr_payload_signed",
                    models.TextField(
                        help_text="Signed PyJWT payload representing the verified tourist identity"
                    ),
                ),
                (
                    "qr_image_base64",
                    models.TextField(
                        blank=True,
                        help_text="Cached Base64-encoded PNG image of the QR code",
                    ),
                ),
                ("issued_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "tourist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="digital_ids",
                        to="identity.tourist",
                    ),
                ),
            ],
            options={
                "ordering": ["-issued_at"],
            },
        ),
    ]
