# Generated by Django 5.1.15 on 2026-08-24 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
        ('journeys', '0001_initial'),
        ('tourists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Personalized Heritage Trip', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('journey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itineraries', to='journeys.journey')),
                ('tourist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to='tourists.touristprofile')),
            ],
            options={
                'verbose_name': 'Itinerary',
                'verbose_name_plural': 'Itineraries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItineraryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(default=1)),
                ('order', models.IntegerField(default=1)),
                ('time', models.CharField(default='09:00 AM', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('duration', models.CharField(default='2 hours', max_length=50)),
                ('transport_mode', models.CharField(choices=[('walk', 'Walking'), ('cab', 'Pre-paid Cab / Taxi'), ('metro', 'Rapid Metro'), ('auto', 'E-Rickshaw / Auto')], default='cab', max_length=20)),
                ('travel_time_from_prev', models.CharField(blank=True, default='15 mins', max_length=50)),
                ('distance_from_prev', models.CharField(blank=True, default='4.5 km', max_length=50)),
                ('cost', models.FloatField(default=0.0)),
                ('safety_status', models.CharField(choices=[('safe', 'Safe Area'), ('caution', 'Caution / High Density')], default='safe', max_length=20)),
                ('recommended_hours', models.CharField(blank=True, default='Morning hours', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('latitude', models.FloatField(default=27.1751)),
                ('longitude', models.FloatField(default=78.0421)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itinerary_items', to='destinations.destination')),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='itinerary.itinerary')),
            ],
            options={
                'verbose_name': 'Itinerary Item',
                'verbose_name_plural': 'Itinerary Items',
                'ordering': ['day', 'order'],
            },
        ),
    ]
