# Generated by Django 5.1.15 on 2026-08-24 19:24

import django.db.models.deletion
import emergency.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tourists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_id', models.CharField(db_index=True, default=emergency.utils.generate_incident_id, max_length=50, unique=True)),
                ('tourist_name', models.CharField(max_length=255)),
                ('tourist_phone', models.CharField(blank=True, max_length=25)),
                ('nationality', models.CharField(default='Indian', max_length=100)),
                ('emergency_type', models.CharField(choices=[('SOS Emergency', 'SOS Emergency Alert'), ('Medical Distress', 'Medical Distress / Health'), ('Missed Check-In', 'Missed Check-In Automated Escalation'), ('Lost Item / Dispute', 'Lost Item / Local Dispute')], db_index=True, default='SOS Emergency', max_length=50)),
                ('priority', models.CharField(choices=[('critical', 'Critical (Immediate Dispatch)'), ('high', 'High Priority'), ('medium', 'Medium Priority'), ('low', 'Low Priority')], default='critical', max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('location_description', models.CharField(default='GPS Coordinates Transmitted', max_length=255)),
                ('description', models.TextField(blank=True, default='Need emergency assistance')),
                ('status', models.CharField(choices=[('new', 'New / Unacknowledged'), ('acknowledged', 'Acknowledged'), ('responding', 'Responders Dispatched'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled by Tourist')], db_index=True, default='new', max_length=20)),
                ('assigned_officer_name', models.CharField(blank=True, default='UP Tourist Police Unit 4', max_length=255)),
                ('battery_level', models.IntegerField(default=100)),
                ('responder_notes', models.TextField(blank=True, default='Emergency signal broadcasted. Nearby rapid response team alerted.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL)),
                ('tourist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_incidents', to='tourists.touristprofile')),
            ],
            options={
                'verbose_name': 'Emergency Incident',
                'verbose_name_plural': 'Emergency Incidents',
                'ordering': ['-created_at'],
            },
        ),
    ]
