# Generated by Django 5.1.6 on 2026-08-17 13:15

import uuid

import django.db.models.deletion
from django.db import migrations, models

import apps.tracking.geo_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="POI",
            fields=[
                (
                    "poi_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the heritage destination / landmark",
                        max_length=200,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        default="Heritage Monument",
                        help_text="Category, e.g. Fort, Palace, Stepwell, Astronomy, Temple",
                        max_length=100,
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        db_index=True,
                        default="Jaipur",
                        help_text="Operational jurisdiction / tourist circuit region",
                        max_length=100,
                    ),
                ),
                ("city", models.CharField(default="Jaipur", max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "history",
                    models.TextField(
                        blank=True,
                        help_text="Detailed archaeological & historical background",
                    ),
                ),
                (
                    "facilities",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of available tourist amenities at the venue",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6, default=26.9855, max_digits=9
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6, default=75.8513, max_digits=9
                    ),
                ),
                (
                    "location",
                    apps.tracking.geo_fields.CompatiblePointField(
                        blank=True,
                        help_text="Spatial Point representation for PostGIS distance queries",
                        null=True,
                    ),
                ),
                (
                    "entry_fee_info",
                    models.CharField(
                        default="₹100 (Indian) • ₹500 (Foreign)",
                        help_text="Official standard entry ticket tariff",
                        max_length=150,
                    ),
                ),
                (
                    "best_time_to_visit",
                    models.CharField(
                        default="October to March, 8:00 AM – 11:00 AM",
                        help_text="Recommended season & time of day",
                        max_length=150,
                    ),
                ),
                (
                    "avg_visit_duration_minutes",
                    models.PositiveIntegerField(
                        default=120,
                        help_text="Average time required to explore this landmark in minutes",
                    ),
                ),
                (
                    "is_hidden_gem",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Distinguishes offbeat/lesser-known spots from famous landmarks",
                    ),
                ),
                (
                    "entry_gate_qr_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique QR ID placed at the physical gate of this monument",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "short_video_url",
                    models.URLField(
                        blank=True,
                        help_text="Short autoplaying video background preview (S3/CDN hosted)",
                        max_length=500,
                    ),
                ),
                (
                    "three_sixty_media_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to 360-degree interactive panorama or virtual tour",
                        max_length=500,
                    ),
                ),
                (
                    "images",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of curated image gallery URLs",
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(decimal_places=2, default=4.8, max_digits=3),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Point of Interest",
                "verbose_name_plural": "Points of Interest",
                "ordering": ["is_hidden_gem", "-rating", "name"],
            },
        ),
        migrations.CreateModel(
            name="AccommodationOption",
            fields=[
                (
                    "accommodation_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("hotel", "Heritage / Boutique Hotel"),
                            ("homestay", "Verified Homestay"),
                            ("hostel", "Backpacker Hostel"),
                        ],
                        default="hotel",
                        max_length=20,
                    ),
                ),
                (
                    "price_range",
                    models.CharField(
                        help_text="Price range, e.g. '₹2,200 – ₹4,500 / night'",
                        max_length=100,
                    ),
                ),
                (
                    "distance_from_poi",
                    models.CharField(
                        help_text="Distance, e.g. '350m from Suraj Pol Gate'",
                        max_length=100,
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(decimal_places=2, default=4.7, max_digits=3),
                ),
                (
                    "verified",
                    models.BooleanField(
                        default=True,
                        help_text="Verified heritage license with police registry",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "poi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accommodation_options",
                        to="poi.poi",
                    ),
                ),
            ],
            options={
                "ordering": ["-rating", "name"],
            },
        ),
        migrations.CreateModel(
            name="TransportOption",
            fields=[
                (
                    "transport_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("taxi", "Pre-Paid Taxi"),
                            ("auto", "Auto-Rickshaw"),
                            ("bus", "Public / Tourist AC Bus"),
                            ("metro", "Jaipur Metro"),
                            ("walk", "Walking Trail"),
                        ],
                        default="taxi",
                        max_length=20,
                    ),
                ),
                (
                    "from_landmark",
                    models.CharField(
                        help_text="Origin point, e.g. 'Jaipur Junction Railway Station' or 'Jaipur International Airport'",
                        max_length=200,
                    ),
                ),
                (
                    "estimated_price_range",
                    models.CharField(
                        help_text="Regulated tariff estimate range, e.g. '₹350 – ₹450' or '₹30 – ₹50 (Bus)'",
                        max_length=100,
                    ),
                ),
                (
                    "estimated_duration",
                    models.CharField(
                        help_text="Estimated travel time, e.g. '30-40 mins'",
                        max_length=100,
                    ),
                ),
                (
                    "verified",
                    models.BooleanField(
                        default=True,
                        help_text="Verified against government pre-paid transport tariffs",
                    ),
                ),
                (
                    "source_verified_by",
                    models.CharField(
                        default="Rajasthan State Transport Authority (RSTA) Tariff 2026",
                        max_length=150,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "poi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transport_options",
                        to="poi.poi",
                    ),
                ),
            ],
            options={
                "ordering": ["mode", "estimated_price_range"],
            },
        ),
    ]
