# Generated by Django 5.1.15 on 2026-08-24 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tourists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField()),
                ('zone_type', models.CharField(choices=[('safe', 'Safe Zone'), ('caution', 'Caution Zone'), ('danger', 'Danger Zone')], db_index=True, default='safe', max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Advisory'), ('high', 'High Alert'), ('critical', 'Critical Hazard')], default='low', max_length=20)),
                ('center_latitude', models.FloatField()),
                ('center_longitude', models.FloatField()),
                ('polygon_coordinates', models.JSONField(default=list, help_text='List of [latitude, longitude] pairs defining the boundary polygon.')),
                ('active_advisory', models.TextField(blank=True, default='')),
                ('tourist_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_safety_zones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Safety Zone',
                'verbose_name_plural': 'Safety Zones',
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SafetyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('alert_type', models.CharField(choices=[('caution', 'Caution'), ('danger', 'Danger / Hazard'), ('info', 'Informational Notice')], db_index=True, default='caution', max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='medium', max_length=20)),
                ('location_name', models.CharField(max_length=255)),
                ('latitude', models.FloatField(db_index=True)),
                ('longitude', models.FloatField(db_index=True)),
                ('alternative_route', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('safety_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='safety.safetyzone')),
            ],
            options={
                'verbose_name': 'Safety Alert',
                'verbose_name_plural': 'Safety Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TouristLocationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('safety_status_determined', models.CharField(default='safe', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('tourist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_logs', to='tourists.touristprofile')),
            ],
            options={
                'verbose_name': 'Tourist Location Log',
                'verbose_name_plural': 'Tourist Location Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
