# Generated by Django 5.1.15 on 2026-08-24 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('tagline', models.CharField(blank=True, max_length=500)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('state', models.CharField(db_index=True, max_length=100)),
                ('category', models.CharField(choices=[('heritage', 'Heritage & Monument'), ('nature', 'Nature & Wildlife'), ('spiritual', 'Spiritual & Pilgrimage'), ('adventure', 'Adventure & Trekking'), ('coastal', 'Coastal & Beach')], db_index=True, default='heritage', max_length=50)),
                ('rating', models.FloatField(default=4.8)),
                ('reviews_count', models.IntegerField(default=0)),
                ('safety_rating', models.FloatField(default=4.8)),
                ('image', models.CharField(max_length=500)),
                ('gallery', models.JSONField(blank=True, default=list)),
                ('description', models.TextField()),
                ('history', models.TextField(blank=True)),
                ('opening_hours', models.CharField(default='06:00 AM – 06:30 PM', max_length=255)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('best_time_to_visit', models.CharField(blank=True, default='October to March', max_length=255)),
                ('entry_fee', models.JSONField(blank=True, default=dict, help_text='{"domestic": 50, "international": 1100, "camera": 25}')),
                ('accessibility', models.JSONField(blank=True, default=dict, help_text='{"wheelchairAccessible": true, "audioAssistance": true, "brailleSignage": true, "batteryCars": true, "specialWashrooms": true}')),
                ('facilities', models.JSONField(blank=True, default=list)),
                ('safety_guidelines', models.JSONField(blank=True, default=list)),
                ('dos_and_donts', models.JSONField(blank=True, default=dict, help_text='{"dos": [...], "donts": [...]}')),
                ('weather', models.JSONField(blank=True, default=dict, help_text='{"temp": 28, "condition": "Clear", "aqi": 85, "aqiStatus": "Good"}')),
                ('crowd_status', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High Peak')], default='moderate', max_length=20)),
                ('crowd_percentage', models.IntegerField(default=50)),
                ('latitude', models.FloatField(db_index=True)),
                ('longitude', models.FloatField(db_index=True)),
                ('qr_code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('panorama_url', models.CharField(blank=True, default='', max_length=500)),
                ('verification_status', models.CharField(choices=[('verified', 'Verified by ASI / Ministry'), ('pending', 'Pending Verification')], default='verified', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Destination',
                'verbose_name_plural': 'Destinations',
                'ordering': ['-rating', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AudioGuideTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='English', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('duration', models.CharField(default='10:00', max_length=20)),
                ('duration_seconds', models.IntegerField(default=600)),
                ('audio_url', models.CharField(max_length=500)),
                ('transcript', models.TextField(blank=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_guides', to='destinations.destination')),
            ],
            options={
                'verbose_name': 'Audio Guide Track',
                'verbose_name_plural': 'Audio Guide Tracks',
            },
        ),
        migrations.CreateModel(
            name='DestinationReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('nationality', models.CharField(default='Indian', max_length=100)),
                ('rating', models.IntegerField(default=5)),
                ('date', models.CharField(default='Recently', max_length=50)),
                ('comment', models.TextField()),
                ('verified_stay', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='destinations.destination')),
            ],
            options={
                'verbose_name': 'Destination Review',
                'verbose_name_plural': 'Destination Reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NearbyAttraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('distance', models.CharField(max_length=50)),
                ('image', models.CharField(blank=True, max_length=500)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nearby_attractions', to='destinations.destination')),
            ],
            options={
                'verbose_name': 'Nearby Attraction',
                'verbose_name_plural': 'Nearby Attractions',
            },
        ),
    ]
