# Generated by Django 5.1.15 on 2026-08-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VerifiedService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('service_type', models.CharField(choices=[('hotel', 'Verified Stay / Heritage Hotel'), ('transport', 'Certified Taxi / Transit'), ('guide', 'Official ASI / RTDC Heritage Guide'), ('ticket', 'Official Monument E-Ticket'), ('experience', 'Curated Cultural Experience'), ('restaurant', 'Verified Culinary / Dining'), ('other', 'Other Tourism Service')], db_index=True, default='guide', max_length=30)),
                ('provider', models.CharField(max_length=255)),
                ('license_number', models.CharField(blank=True, default='', max_length=100)),
                ('location', models.CharField(db_index=True, max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('rating', models.FloatField(default=4.9)),
                ('reviews_count', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0.0)),
                ('price_unit', models.CharField(default='per person', max_length=100)),
                ('image', models.CharField(max_length=500)),
                ('badge', models.CharField(default='✓ SafarSetu Verified', max_length=100)),
                ('facilities', models.JSONField(blank=True, default=list)),
                ('accessibility', models.JSONField(blank=True, default=list)),
                ('cancellation_policy', models.TextField(blank=True, default='Free cancellation up to 24 hours prior.')),
                ('is_verified', models.BooleanField(db_index=True, default=True)),
                ('verified_date', models.CharField(default='Verified Quarterly Audit', max_length=100)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('experience_years', models.IntegerField(blank=True, default=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Verified Service',
                'verbose_name_plural': 'Verified Services',
                'ordering': ['-rating', 'title'],
            },
        ),
    ]
