# Generated by Django 5.1.15 on 2026-08-24 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
        ('tourists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code_scanned', models.CharField(db_index=True, max_length=255)),
                ('scan_type', models.CharField(choices=[('DESTINATION', 'Destination Monument QR'), ('DIGITAL_ID', 'Tourist Digital ID Check'), ('SERVICE', 'Verified Service QR'), ('OTHER', 'General QR')], default='DESTINATION', max_length=20)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('scanned_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_scans', to='destinations.destination')),
                ('tourist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_scans', to='tourists.touristprofile')),
            ],
            options={
                'verbose_name': 'QR Scan Log',
                'verbose_name_plural': 'QR Scan Logs',
                'ordering': ['-scanned_at'],
            },
        ),
    ]
